camunda.bpm:
  admin-user: # user-id, password, user-name for camunda web app
    id: demo
    password: demo
    firstName: Demo
  filter:
    create: All tasks # the name for "show all" filter
  client:
    base-url: http://localhost:8080/engine-rest
    lock-duration: 10000
    subscriptions:
      scoreProvider: # topic name of the External Service Task
        variable-names: [] # our business logic doesn't require any variables, so don't fetch them
        process-definition-key: loan_process # only filter for External Tasks with this process definition key
      loanGranter:
        variable-names: customerId, creditScore # only fetch these two variables
        process-definition-key: loan_process

spring:
  quartz:
    job-store-type: jdbc # store jobs in h2 database, change this to "memory" for in-memory storage
    properties.org.quartz:
      scheduler:
        instanceId: AUTO
      threadPool:
        threadCount: 4
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
  datasource:
    platform: h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  file: log/${spring.application.name}.log
  level:
    root: WARN
    org.bkcloud.fleet.workflow: DEBUG
    org.springframework.data.jpa: INFO
