camunda.bpm:
  admin-user: # user-id, password, user-name for camunda web app
    id: demo
    password: demo
    firstName: Demo
  filter:
    create: All tasks # the name for "show all" filter

spring:
  quartz:
    job-store-type: jdbc # store jobs in h2 database, change this to "memory" for in-memory storage
    properties.org.quartz:
      scheduler:
        instanceId: AUTO
      threadPool:
        threadCount: 4
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftlh
  datasource:
    platform: h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  file: log/workflow.log
  level:
    root: WARN
    org.bkcloud.fleet.workflow: DEBUG
    org.springframework.data.jpa: INFO
